"""phasmorpg.py"""
traits = [
            ["Archaeologist","Must find the bone as a priority. Can't do anything else until it is found"],
            ["Atmospheric","Can only use the candle for light"],
            ["Attached","Must be in the same room as another player at all times. Even during hunts."],
            ["Back Pain","Must be crouched at all times"],
            ["Bold","Can't use the crucifix"],
            ["Chatterbox","Must always talk to the ghost when near it, say its name, asks for signs, etc. including during hunts"],
            ["Chilly","Must keep the breaker on at all times"],
            ["Clumsy","Must drop all items when a hunt begins"],
            ["Courteous","You must close every door behind you, even during hunts"],
            ["Coward","If you experience a ghost event, you must retreat to the truck and stay until you're the highest sanity player"],
            ["Crabrave","You can only walk from side to side"],
            ["Deafened","Sound must be off. You can still talk"],
            ["Disoriented","Headphones must be reversed"],
            ["Forgetful","Lose two random items from the mission"],
            ["Germophobe","Must wash your hands every time you pass or are in a room with a sink (permitted there's no dirty water)"],
            ["Impulsive","If there is a ghost event, you must drop what is in your hand out of fear. It is now broken and can't be reused"],
            ["Inconsiderate","Every door you open you must leave open, including during hunts"],
            ["Inquisitive","If you find the Ouija board, you immediately have to use it until you get a successful answer"],
            ["Insane","Cannot check your sanity or take sanity pills"],
            ["Limp","Can't sprint during hunts"],
            ["Loner","Can't be in the same room as another player, including during hunts"],
            ["Metalhead","Must have a playlist playing at moderate volume as if wearing headphones while ghosthunting"],
            ["Nycotophobic","Must keep lights on in the room you're in at all times. If breaker goes off, fix immediately"],
            ["Oversized","Can't hide in lockers or closets"],
            ["Paranoid","Can't hide in the same place more than once"],
            ["Perceptive","Must use eyes and ears only to find the ghost room"],
            ["Photophobic","Can't use building lights"],
            ["Raver","Can only use glowsticks for light"],
            ["Reckless","Can't use Smudge Sticks"],
            ["Recycler","Must bring all items back to the truck"],
            ["Rushed","Not allowed to check the breaker location on truck monitor"],
            ["Shy","Not allowed to talk to the ghost (e.g. Spirit Box or Board)"],
            ["Small Pockets","Can only carry 2 items"],
            ["Thick Jumper","Must keep the breaker off at all times"],
            ["Thief","Must steal any valuables"],
            ["Tidy","Must put every item back where it belongs if your fellow hunters or ghosts move them"],
            ["Unprepared","Can't look at information on the whiteboard"],
            ["Useless","Can't use evidence gathering equipment"],
            ["UV Expert","Can only use UV Torch for light"],
            ["Vlogger","Must hold a video camera and vlog at all times"],
            ["Weak Bladder","Must use the toilet every time you directly pass a room with a toilet in it"],
            ["Young at Heart","Must rescuse any stuffed toys and bring them back to the truck"]]

personalities = [
            "Aussie",
            "Caveman",
            "Frenchman",
            "Brit",
            "German",
            "Ghost Hunter",
            "Japanese",
            "Joker",
            "Rilk",
            "Scooby",
            "Shaggy",
            "Suh Dude"]

items = [
            "D.O.T.S Projector",
            "EMF Reader",
            "Flashlight",
            "Ghost Writing Book",
            "Spirit Box",
            "UV Light",
            "Video Camera",
            # Gap on whiteboard in-game
            "Candle",
            "Crucifix",
            "Glowstick",
            "Head Mounted Camera",
            "Lighter",
            "Motion Sensor",
            "Parabolic Microphone",
            "Photo Camera",
            "Salt",
            "Sanity Pills",
            "Smudge Sticks",
            "Sound Sensor",
            "Strong Flashlight",
            "Thermometer",
            "Tripod"]